name: Run job if any dependency succeeds
on:
  push:
    branches: [ main ]
jobs:
  dep1:
    runs-on: ubuntu-latest
    steps:
      - name: Run FAILING script
        run: exit 1 
  nextjob:
    runs-on: ubuntu-latest
    if: ${{ always() }}
    needs: [dep1]
    steps:
      - name: Hello World        
        env:
          NEEDS: ${{ toJSON(needs) }}     
        run: |
          echo "$NEEDS"
