name: My Workflow

on:
  workflow_dispatch:

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Step 1 - Job 1
        run: echo "Job 1"

  job2:
    runs-on: ubuntu-latest
    needs: job1
    if: ${{ needs.job1.result == 'success' }}
    steps:
      - name: Step 1 - Job 2
        run: echo "Job 2"

  job3:
    runs-on: ubuntu-latest
    needs: job2
    if: ${{ needs.job2.result == 'success' }}
    steps:
      - name: Step 1 - Job 3
        run: echo "Job 3"

  job4:
    runs-on: ubuntu-latest
    needs: job3
    if: ${{ needs.job3.result == 'success' }}
    steps:
      - name: Step 1 - Job 4 (Intentional Failure)
        run: exit 1  # Intentionally exit with a non-zero code to indicate failure

  job5:
    runs-on: ubuntu-latest
    needs: job4
    if: ${{ needs.job4.result == 'success' }}
    steps:
      - name: Step 1 - Job 5
        run: echo "Job 5"
