name: \\\\\\\\\\\\\\\\\\\\\\\\

on:
  workflow_dispatch:

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
       - name: Continue on Error
         continue-on-error: ${{ github.event.inputs.continue_on_error == 'true' }}
       - name: Step 1 - Job 4 (Intentional Failure)
         run: exit 1


  job2:
    runs-on: ubuntu-latest
    needs: job1
    steps:
      - name: Step 1 - Job 2
        run: echo "Job 2"
