name: design error
on: [workflow_dispatch]

permissions:

    contents: read
    checks: write
    
jobs:
  Run_Tests:
    runs-on: self-hosted
    steps:
     - name: Launch matlab
       run: |
         $pathToAdd = "\\mathworks\devel\sbs\37\vanshg.Bslcicd.j2276893.1\matlab\bin"
         $env:PATH += ";$pathToAdd"
         $env:PATH | Add-Content -Path $env:GITHUB_PATH
         matlab -nodesktop -logfile output.log -batch "openProject(pwd);runprocess(Tasks = {'padv.builtin.task.RunTestsPerTestCase|sl_test_case|ProcessAdvisorExample|02_Models/AHRS_Voter/test_cases/AHRS_Voter_REQ_Based_Test.mldatx|74194125-b632-41a1-b96d-b3364441277f','padv.builtin.task.RunTestsPerTestCase|sl_test_case|ProcessAdvisorExample|02_Models/AHRS_Voter/test_cases/AHRS_Voter_REQ_Based_Test.mldatx|ced877ff-cfb8-4fa8-9bbf-aaa29b1d926b','padv.builtin.task.RunTestsPerTestCase|sl_test_case|ProcessAdvisorExample|02_Models/AHRS_Voter/test_cases/AHRS_Voter_REQ_Based_Test.mldatx|d3a72cc8-687b-44ae-a909-7eff803b455b','padv.builtin.task.RunTestsPerTestCase|sl_test_case|ProcessAdvisorExample|02_Models/OuterLoop_Control/test_cases/OuterLoop_Control_REQ_Based_Test.mldatx|51b0cb29-34f5-4c04-9104-4f3b0b48dda9','padv.builtin.task.RunTestsPerTestCase|sl_test_case|ProcessAdvisorExample|02_Models/OuterLoop_Control/test_cases/OuterLoop_Control_REQ_Based_Test.mldatx|70d344b2-d65f-4872-9e4b-cef338e618a5','padv.builtin.task.RunTestsPerTestCase|sl_test_case|ProcessAdvisorExample|02_Models/OuterLoop_Control/test_cases/OuterLoop_Control_REQ_Based_Test.mldatx|862932e4-be44-4f66-9abe-fb313da73c0d'}, Force = false, ExitInBatchMode = true, RerunFailedTasks = false, RerunErroredTasks = false, GenerateJUnitForProcess = true);"
            
     - name: Upload JUnit XML artifacts
       uses: actions/upload-artifact@v2
       with:
         name: JUnit XML
         path: |
           04_Results/junit/padv_builtin_task_RunTestsPerTestCase_HLR_11_JUnit.xml
           04_Results/junit/padv_builtin_task_RunTestsPerTestCase_HLR_12_JUnit.xml
           04_Results/junit/padv_builtin_task_RunTestsPerTestCase_HLR_13_JUnit.xml
           04_Results/junit/padv_builtin_task_RunTestsPerTestCase_HLR_6_JUnit.xml
           04_Results/junit/padv_builtin_task_RunTestsPerTestCase_HLR_7_JUnit.xml
           04_Results/junit/padv_builtin_task_RunTestsPerTestCase_HLR_8_JUnit.xml


     - name: HLR_11
       uses: mikepenz/action-junit-report@v3
       with:
          name: AHRS_Voter
          report_paths: 04_Results/junit/padv_builtin_task_RunTestsPerTestCase_HLR_11_JUnit.xml

            
     - name: HLR_12
       uses: mikepenz/action-junit-report@v3
       with:
          name: Actuator_Control
          report_paths: 04_Results/junit/padv_builtin_task_RunTestsPerTestCase_HLR_12_JUnit.xml
      
     - name: HLR_13
       uses: mikepenz/action-junit-report@v3
       with:
          name: Flight_Control
          report_paths: 04_Results/junit/padv_builtin_task_RunTestsPerTestCase_HLR_13_JUnit.xml

     - name: HLR_6
       uses: mikepenz/action-junit-report@v3
       with:
          name: InnerLoop_Control
          report_paths: 04_Results/junit/padv_builtin_task_RunTestsPerTestCase_HLR_6_JUnit.xml
            
     - name: HLR_7
       uses: mikepenz/action-junit-report@v3
       with:
          name: OuterLoop_Control
          report_paths: 04_Results/junit/padv_builtin_task_RunTestsPerTestCase_HLR_7_JUnit.xml
          
     - name: HLR_8
       uses: mikepenz/action-junit-report@v3
       with:
          name: OuterLoop_Control
          report_paths: 04_Results/junit/padv_builtin_task_RunTestsPerTestCase_HLR_8_JUnit.xml
            
 
            
     
