name: design error
on: [workflow_dispatch]


    
jobs:
  Detect_Design_Errors:
    runs-on: self-hosted
    steps:
     - name: Launch matlab
       run: |
         $pathToAdd = "\\mathworks\devel\sbs\37\vanshg.Bslcicd.j2276893.1\matlab\bin"
         $env:PATH += ";$pathToAdd"
         $env:PATH | Add-Content -Path $env:GITHUB_PATH
         matlab -nodesktop -logfile output.log -batch "openProject(pwd);runprocess(Tasks = {'padv.builtin.task.DetectDesignErrors|sl_model_file|ProcessAdvisorExample|02_Models/AHRS_Voter/specification/AHRS_Voter.slx','padv.builtin.task.DetectDesignErrors|sl_model_file|ProcessAdvisorExample|02_Models/Actuator_Control/specification/Actuator_Control.slx','padv.builtin.task.DetectDesignErrors|sl_model_file|ProcessAdvisorExample|02_Models/Flight_Control/specification/Flight_Control.slx','padv.builtin.task.DetectDesignErrors|sl_model_file|ProcessAdvisorExample|02_Models/InnerLoop_Control/specification/InnerLoop_Control.slx','padv.builtin.task.DetectDesignErrors|sl_model_file|ProcessAdvisorExample|02_Models/OuterLoop_Control/specification/OuterLoop_Control.slx'}, Force = false, ExitInBatchMode = true, RerunFailedTasks = false, RerunErroredTasks = false, GenerateJUnitForProcess = true);" 
     - name: Upload JUnit XML artifacts
       uses: actions/upload-artifact@v2
       with:
         name: JUnit XML
         path: |
             04_Results/junit/padv_builtin_task_DetectDesignErrors_AHRS_Voter_JUnit.xml
             04_Results/junit/padv_builtin_task_DetectDesignErrors_Actuator_Control_JUnit.xml
             04_Results/junit/padv_builtin_task_DetectDesignErrors_Flight_Control_JUnit.xml
             04_Results/junit/padv_builtin_task_DetectDesignErrors_InnerLoop_Control_JUnit.xml
             04_Results/junit/padv_builtin_task_DetectDesignErrors_OuterLoop_Control_JUnit.xml
             
     - name: AHRS_Voter_JUnit
       uses: mikepenz/action-junit-report@v3
       with:
          name: AHRS_Voter
          report_paths: 04_Results/junit/padv_builtin_task_DetectDesignErrors_AHRS_Voter_JUnit.xml

            
     - name: Actuator_Control_JUnit
       uses: mikepenz/action-junit-report@v3
       with:
          name: Actuator_Control
          report_paths: 04_Results/junit/padv_builtin_task_DetectDesignErrors_Actuator_Control_JUnit.xml
      
     - name: Flight_Control_JUnit
       uses: mikepenz/action-junit-report@v3
       with:
          name: Flight_Control
          report_paths: 04_Results/junit/padv_builtin_task_DetectDesignErrors_Flight_Control_JUnit.xml

     - name: InnerLoop_Control_JUnit
       uses: mikepenz/action-junit-report@v3
       with:
          name: InnerLoop_Control
          report_paths: 04_Results/junit/padv_builtin_task_DetectDesignErrors_InnerLoop_Control_JUnit.xml
            
     - name: OuterLoop_Control_JUnit
       uses: mikepenz/action-junit-report@v3
       with:
          name: OuterLoop_Control
          report_paths: 04_Results/junit/padv_builtin_task_DetectDesignErrors_OuterLoop_Control_JUnit.xml
     
