name: Execution Workflow

on:
  workflow_dispatch:

jobs:
  transfer_file:
    runs-on: self-hosted

    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: Transfer the contents
        run: |
           echo F | xcopy ".github\workflows\xyz.yaml" ".github\workflows\simulink_workflow.yml" /Y /I
         
         
        # $sourceContent = Get-Content -Raw -Path .github/workflows/xyz.yaml
         #$sourceContent | Set-Content -Path .github/workflows/simulink_workflow.yml
         
      - name: Configure Git
        run: |
          git config --global user.name "Vansh Gandhi"
          git config --global user.email "vansh20147@iiitd.ac.in"

      - name: Commit changes
        run: |
          git add .github/workflows/simulink_workflow.yml
          git commit -m "Update simulink_workflow.yml"
        
      - name: Push changes
        run: |
          git push
        
  Execution:
    runs-on: self-hosted
    needs: transfer_file
    
    steps:
      - name : Execution
        run: echo "simulink_workflow will execute after this workflow"
      
