name: Execution Workflow

on:
  workflow_dispatch:

env:
  PATH_TO_MATLAB:
    /mathworks/BGL/devel/sbs/37/vanshg.Bslcicd.j2291166/matlab/bin
jobs:
  transfer_file:
    runs-on: Linux

    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.ACTIONS_SECRET }}
      - name:
          Setup Matlab
        run:
         |
          export PATH="$PATH_TO_MATLAB:$PATH"
          echo "$PATH" >> $GITHUB_PATH 
#       - name: generate pipeline
#         uses: matlab-actions/run-command@v1
#         with:
#           command: "script"
#           startup-options:
#             -nodesktop -logfile output.log
#       - name: Transfer the contents
#         run: |
#            cp derived/pipeline/pipeline.yml .github/workflows/simulink_workflow.yml 
      - name: Pushes test file
        uses: dmnemec/copy_file_to_another_repo_action@main
        env:
          token: ${{ secrets.ACTIONS_SECRET }}
        with:
          source_file: '.github/workflows/simulink_workflow.yml'
          destination_repo: 'Actions-test'
          destination_folder: '.github/workflows'
          user_email: 'vansh20147@iiitd.ac.in'
          user_name: 'vansh2552'
          commit_message: 'A custom message for the commit'
          
#       - name: Transfer the contents
#         run: |
#            cp derived/pipeline/pipeline.yml .github/workflows/simulink_workflow.yml 
         
         
#       - name: Configure Git
      
#         run: |
#           #git config user.name github-actions[bot]
#           #git config user.email 41898282+github-actions[bot]@users.noreply.github.com

#            git config user.name "Vansh Gandhi"
#            git config user.email vansh20147@iiitd.ac.in
#       - name: Commit changes and push
#         run: |
#           git add .
#           git commit -m "Update simulink_workflow.yml"
#           git push


#   call-workflow:
#     uses: vansh2552/Actions-test/.github/workflows/simulink_workflow.yml@master
 
      
