name: Execution Workflow

on:
  workflow_dispatch:
    inputs:
      target-workflow:
        description: 'Target workflow to run'
        required: true

jobs:
  transfer_file:
    runs-on: self-hosted

    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.ACTIONS_SECRET }}
      - name: Transfer the contents
        run: |
           echo F | xcopy ".github\workflows\xyz.yaml" ".github\workflows\simulink_workflow.yml" /Y /I
         
      - name: Configure Git
      
        run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com
      - name: Commit changes
        run: |
          git add .github/workflows/simulink_workflow.yml
          git commit -m "Update simulink_workflow.yml"
        
      - name: Push changes
        env:
          PAT_TOKEN: ${{ secrets.ACTIONS_SECRET}}
        run: |
          echo $ACTIONS_SECRET
          git push
        
  Execution:
    runs-on: self-hosted
    needs: transfer_file
    
    steps:
      - name: Trigger Workflow
        uses: peter-evans/workflow-dispatch@v1
        with:
          workflow: ${{ github.event.inputs.target-workflow }}
          
#       - name : Execution
#         run: echo "simulink_workflow will execute after this workflow"
      
