name: Execution Workflow

on:
  workflow_dispatch:


jobs:
  transfer_file:
    runs-on: self-hosted

    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.ACTIONS_SECRET }}
          
      - name: Transfer the contents
        run: |
           echo F | xcopy ".github\workflows\xyz.yaml" ".github\workflows\simulink_workflow.yml" /Y /I
         
#       - name: Configure Git
      
#         run: |
#           #git config user.name github-actions[bot]
#           #git config user.email 41898282+github-actions[bot]@users.noreply.github.com

#            git config user.name "Vansh Gandhi"
#            git config user.email vansh20147@iiitd.ac.in
#       - name: Commit changes and push
#         run: |
#           git add .github/workflows/simulink_workflow.yml
#           git commit -m "Update simulink_workflow.yml"
#           git push
          
        
  Execution:
    runs-on: self-hosted
    needs: transfer_file
    
    steps: 
         
       - name: Execute Workflow
         uses: peter-evans/repository-dispatch@v1
         with:
           token: ${{ secrets.ACTIONS_SECRET }}
           event-type: run-child-workflow
 
      
