name: Execution Workflow

on:
  workflow_dispatch:

jobs:
  transfer_file:
    runs-on: self-hosted

    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: Transfer the contents
        run: |
           xcopy ".github\\workflows\\xyz.yaml" ".github\\workflows\\simulink_workflow.yml" /Y /I /F
         
         
        # $sourceContent = Get-Content -Raw -Path .github/workflows/xyz.yaml
         #$sourceContent | Set-Content -Path .github/workflows/simulink_workflow.yml
        
  Execution:
    runs-on: self-hosted
    needs: transfer_file
    
    steps:
      - name : Execution
        run: echo "simulink_workflow will execute after this workflow"
      
