name: Execution Workflow

on:
  workflow_dispatch:

jobs:
  transfer_file:
    runs-on: self-hosted

    steps:
      - name: Transfer the contents
        run: Copy-Item -Path ".github\\workflows\\env.yml" -Destination ".github\\workflows\\simulink_workflow.yml" -Force  
        
  Execution:
    runs-on: self-hosted
    needs: transfer_file
    
    steps:
      - name : Execution
        run: echo "simulink_workflow will execute after this workflow"
      
