name: pipeline
on: [push]
 

jobs:
  Generate_Simulink_Web_View:
    runs-on: self-hosted
    env:
     ACTIONS_ALLOW_UNSECURE_COMMANDS: true
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Cache files
        uses: actions/cache@v2
        with:
          path: |
            04_Results/AHRS_Voter/code_inspection
            04_Results/AHRS_Voter/coding_standards
            04_Results/AHRS_Voter/design_error_detections
            04_Results/AHRS_Voter/model_standards_results
            04_Results/AHRS_Voter/system_design_description
            04_Results/AHRS_Voter/webview
            04_Results/Actuator_Control/code_inspection
            04_Results/Actuator_Control/coding_standards
            04_Results/Actuator_Control/design_error_detections
            04_Results/Actuator_Control/model_standards_results
            04_Results/Actuator_Control/system_design_description
            04_Results/Actuator_Control/webview
            04_Results/Flight_Control/code_inspection
            04_Results/Flight_Control/coding_standards
            04_Results/Flight_Control/design_error_detections
            04_Results/Flight_Control/model_standards_results
            04_Results/Flight_Control/system_design_description
            04_Results/Flight_Control/webview
            04_Results/InnerLoop_Control/code_inspection
            04_Results/InnerLoop_Control/coding_standards
            04_Results/InnerLoop_Control/design_error_detections
            04_Results/InnerLoop_Control/model_standards_results
            04_Results/InnerLoop_Control/system_design_description
            04_Results/InnerLoop_Control/webview
            04_Results/OuterLoop_Control/code_inspection
            04_Results/OuterLoop_Control/coding_standards
            04_Results/OuterLoop_Control/design_error_detections
            04_Results/OuterLoop_Control/model_standards_results
            04_Results/OuterLoop_Control/system_design_description
            04_Results/OuterLoop_Control/webview
            04_Results/test_results
          key: cached-files

           

          
      - name: Run the matlab version
        run: |
         echo "PATH=$HOME/\\mathworks\devel\sbs\37\vanshg.Bslcicd.j2276893.1\matlab\bin:$PATH" >> $GITHUB_ENV
         #echo "\\mathworks\devel\sbs\37\vanshg.Bslcicd.j2276893.1\matlab\bin" >> $env:GITHUB_PATH
         echo $env:PATH

         #matlab -nodesktop -logfile output.log -batch "disp('Hello, MATLAB!');"
#             #
#             echo "$\\mathworks\devel\sbs\37\vanshg.Bslcicd.j2276893.1\matlab\bin" >> $GITHUB_PATH
#             echo $MY_VARIABLE




          



      

