name:  Parent Workflow

on:
  workflow_dispatch:

jobs:
  trigger_child_workflow_job:
    runs-on: self-hosted

    steps:
      - name: Trigger Child Workflow
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.ACTIONS_SECRET }}
          event-type: run-child-workflow
          
      - name: Another step
        run: echo "hello"
