name: pipeline3
on:
  workflow_dispatch:


permissions:
    contents: read
    checks: write
    
env:
  PATH_TO_MATLAB: "\\\\mathworks\\BGL\\devel\\sbs\\37\\vanshg.Bslcicd.j2276893.1\\matlab\\bin"

  
jobs:
  AHRS_Generate_Simulink_Web_View:
    runs-on: self-hosted1
    #if: ${{ always() }}
    steps:


    
      - name: Run the matlab version
        run: $env:PATH = "$env:PATH_TO_MATLAB"+$env:PATH; $env:PATH | Add-Content -Path $env:GITHUB_PATH

         
      - name: Launch MATLAB
        uses: matlab-actions/run-command@v1
        with:
             command: "openProject(pwd);runprocess(Tasks = {'padv.builtin.task.GenerateSimulinkWebView|sl_model_file|ProcessAdvisorExample|02_Models/AHRS_Voter/specification/AHRS_Voter.slx'}, Force=false,ExitInBatchMode = true, RerunFailedTasks = false,RerunErroredTasks = false,GenerateJUnitForProcess = true);"
             startup-options: -nodesktop -logfile output.log

          
  AHRS_Check_Modeling_Standards:
   runs-on: self-hosted1

   needs: AHRS_Generate_Simulink_Web_View
   steps:
   
     
   - name: Run the matlab version
     run: $env:PATH ="$env:PATH_TO_MATLAB" +  $env:PATH ; $env:PATH | Add-Content -Path $env:GITHUB_PATH  
        
   - name: Launch MATLAB
     uses: matlab-actions/run-command@v1
     with:
         command: "openProject(pwd);runprocess(Tasks = {'padv.builtin.task.RunModelStandards|sl_model_file|ProcessAdvisorExample|02_Models/AHRS_Voter/specification/AHRS_Voter.slx'}, Force=false,ExitInBatchMode = true, RerunFailedTasks = false,RerunErroredTasks = false,GenerateJUnitForProcess = true);"
         startup-options: -nodesktop -logfile output.log
 

   
