name:
  pipeline3
on:
  workflow_dispatch:


permissions:
  checks:
    write

  contents:
    read
    
env:
  PATH_TO_MATLAB: "/mathworks/BGL/devel/sbs/37/vanshg.Bslcicd.j2291166/matlab/bin"

  
jobs:
  AHRS_Generate_Simulink_Web_View:
    runs-on: ubuntu-latest
    #if: ${{ always() }}
    steps:
    
      - name: Checkout repository
        uses: actions/checkout@v2



        
      - name: Run the matlab version
        shell: bash
        run: |
        
          export PATH="$PATH_TO_MATLAB:$PATH"
          echo "$PATH" >> $GITHUB_PATH
         


          
