name: pipeline3
on:
  workflow_dispatch:


permissions:
    contents: read
    checks: write
    
env:
  PATH_TO_MATLAB: "\\\\mathworks\\devel\\sbs\\37\\vanshg.Bslcicd.j2291166\\matlab\\bin"

  
jobs:
  AHRS_Generate_Simulink_Web_View:
    runs-on: Windows
    #if: ${{ always() }}
    steps:


      - name: Cache files
        uses: actions/cache@v2
        with:
          path: |
            04_Results/AHRS_Voter/code_inspection
            04_Results/AHRS_Voter/coding_standards
            04_Results/AHRS_Voter/design_error_detections
            04_Results/AHRS_Voter/model_standards_results
            04_Results/AHRS_Voter/system_design_description
            04_Results/AHRS_Voter/webview
            04_Results/Actuator_Control/code_inspection
            04_Results/Actuator_Control/coding_standards
            04_Results/Actuator_Control/design_error_detections
            04_Results/Actuator_Control/model_standards_results
            04_Results/Actuator_Control/system_design_description
            04_Results/Actuator_Control/webview
            04_Results/Flight_Control/code_inspection
            04_Results/Flight_Control/coding_standards
            04_Results/Flight_Control/design_error_detections
            04_Results/Flight_Control/model_standards_results
            04_Results/Flight_Control/system_design_description
            04_Results/Flight_Control/webview
            04_Results/InnerLoop_Control/code_inspection
            04_Results/InnerLoop_Control/coding_standards
            04_Results/InnerLoop_Control/design_error_detections
            04_Results/InnerLoop_Control/model_standards_results
            04_Results/InnerLoop_Control/system_design_description
            04_Results/InnerLoop_Control/webview
            04_Results/OuterLoop_Control/code_inspection
            04_Results/OuterLoop_Control/coding_standards
            04_Results/OuterLoop_Control/design_error_detections
            04_Results/OuterLoop_Control/model_standards_results
            04_Results/OuterLoop_Control/system_design_description
            04_Results/OuterLoop_Control/webview
            04_Results/test_results
          key: cached-files
        
      - name: Run the matlab version
        run: $env:PATH += ";$env:PATH_TO_MATLAB"; $env:PATH | Add-Content -Path $env:GITHUB_PATH
        
      - name: Check Runner Shell
        run: |
          if [ "${{ runner.os }}" == "Windows" ]; then
            echo "The runner is using Windows."
            echo "The shell being used is $env:ComSpec"  # PowerShell or cmd
          else
            echo "The runner is using ${{ runner.os }}."
            echo "The shell being used is $SHELL"  # Default shell on non-Windows systems
          fi


         

       
      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
         name: artifacts
         path: 04_Results/AHRS_Voter/webview
 
          

          
  AHRS_Check_Modeling_Standards:
   runs-on: Windows
   if: ${{ always() }}
   needs: AHRS_Generate_Simulink_Web_View
   steps:
   
     
   - name: Run the matlab version
     run: $env:PATH += ";$env:PATH_TO_MATLAB"; $env:PATH | Add-Content -Path $env:GITHUB_PATH  
        

         
   - name: Download Artifacts
     uses: actions/download-artifact@v2
     with:
          name: artifacts

   - name: Extract Contents
     uses: actions/extract@v1
     with:
          archive-file: artifacts.zip
          output-directory: artifacts
          
   - name: Append Contents to Downloaded Folder
     run: |
          cp -R 04_Results/AHRS_Voter/model_standards_results/* artifacts/


   - name: Upload Updated Artifacts
     uses: actions/upload-artifact@v2
     with:
        name: updated-artifacts
        path: artifacts
  
          

   
 
    
