name: pipeline3
on:
  workflow_dispatch:


permissions:
    contents: read
    checks: write
    
env:
  PATH_TO_MATLAB: "\\\\mathworks\\devel\\sbs\\37\\vanshg.Bslcicd.j2291166\\matlab\\bin"

  
jobs:
  AHRS_Generate_Simulink_Web_View:
    runs-on: Windows
    #if: ${{ always() }}
    steps:


      - name: Cache files
        uses: actions/cache@v2
        with:
          path: |
            04_Results/AHRS_Voter/code_inspection
            04_Results/AHRS_Voter/coding_standards
            04_Results/AHRS_Voter/design_error_detections
            04_Results/AHRS_Voter/model_standards_results
            04_Results/AHRS_Voter/system_design_description
            04_Results/AHRS_Voter/webview

          key: cached-files
        
      - name: Run the matlab version
        run: $env:PATH += ";$env:PATH_TO_MATLAB"; $env:PATH | Add-Content -Path $env:GITHUB_PATH
        
      - name: create a folder
        run: |
            mkdir artifacts
      - name: Transfer files
        run: xcopy "04_Results\\AHRS_Voter\\webview\\*" "artifacts" /E /I


         

       
      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
         name: artifacts_folder
         path: artifacts
 
          

          
  AHRS_Check_Modeling_Standards:
   runs-on: Windows
   if: ${{ always() }}
   needs: AHRS_Generate_Simulink_Web_View
   steps:
   
     
   - name: Run the matlab version
     run: $env:PATH += ";$env:PATH_TO_MATLAB"; $env:PATH | Add-Content -Path $env:GITHUB_PATH  
        

         
   - name: Download Artifacts
     uses: actions/download-artifact@v2
     with:
          name: artifacts


   
 
    
