name: pipeline3
on: [workflow_dispatch]
  
jobs:
  AHRS_Generate_Simulink_Web_View:
    runs-on: self-hosted
   
    steps:

             
      - name: Run the matlab version
        run: |
         $pathToAdd = "\\\\mathworks\\devel\\sbs\\37\\vanshg.Bslcicd.j2276893.1\\matlab\\bin"
         $env:PATH = "$pathToAdd" + $env:PATH 
         $env:PATH | Add-Content -Path $env:GITHUB_PATH
          
         
      - name: Print path
        run: echo "$env:GITHUB_PATH" 
         
      - name: Launch MATLAB
        uses: matlab-actions/run-command@v1
        with:
             command: "openProject(pwd);runprocess(Tasks = {'padv.builtin.task.GenerateSimulinkWebView|sl_model_file|ProcessAdvisorExample|02_Models/AHRS_Voter/specification/AHRS_Voter.slx'}, Force=false,ExitInBatchMode = true, RerunFailedTasks = false,RerunErroredTasks = false,GenerateJUnitForProcess = true);"
             startup-options: -nodesktop -logfile output.log
 
          
  AHRS_Check_Modeling_Standards:
   runs-on: self-hosted
   needs: AHRS_Generate_Simulink_Web_View
   steps:
   
   - name: Run the matlab version
     run: |
         $pathToAdd = "\\mathworks\devel\sbs\37\vanshg.Bslcicd.j2276893.1\matlab\bin"
         $env:PATH += ";$pathToAdd"
         $env:PATH | Add-Content -Path $env:GITHUB_PATH
         
   - name: Launch MATLAB
     uses: matlab-actions/run-command@v1
     with:
         command: "openProject(pwd);runprocess(Tasks = {'padv.builtin.task.RunModelStandards|sl_model_file|ProcessAdvisorExample|02_Models/AHRS_Voter/specification/AHRS_Voter.slx'}, Force=false,ExitInBatchMode = true, RerunFailedTasks = false,RerunErroredTasks = false,GenerateJUnitForProcess = true);"
         startup-options: -nodesktop -logfile output.log
         
   - name: Upload JUnit XML artifacts
     uses: actions/upload-artifact@v2
     with:
         name: JUnit XML
         path: |
          04_Results/junit/padv_builtin_task_RunModelStandards_AHRS_Voter_JUnit.xml
          
   - name: AHRS_Voter_JUnit
     uses: mikepenz/action-junit-report@v3
     with:
        name: AHRS_Voter
        report_paths: 04_Results/junit/padv_builtin_task_RunModelStandards_AHRS_Voter_JUnit.xml
   
  AHRS_Detect_Design_Errors:
   runs-on: self-hosted
   needs: AHRS_Check_Modeling_Standards
   steps:


         
   - name: Launch MATLAB
     uses: matlab-actions/run-command@v1
     with:
         command: "openProject(pwd);runprocess(Tasks = {'padv.builtin.task.RunModelStandards|sl_model_file|ProcessAdvisorExample|02_Models/AHRS_Voter/specification/AHRS_Voter.slx'}, Force=false,ExitInBatchMode = true, RerunFailedTasks = false,RerunErroredTasks = false,GenerateJUnitForProcess = true);"
         startup-options: -nodesktop -logfile output.log
         
   - name: Upload JUnit XML artifacts
     uses: actions/upload-artifact@v2
     with:
         name: JUnit XML
         path: |
          04_Results/junit/padv_builtin_task_RunModelStandards_AHRS_Voter_JUnit.xml
          
   - name: AHRS_Voter_JUnit
     uses: mikepenz/action-junit-report@v3
     with:
        name: AHRS_Voter
        report_paths: 04_Results/junit/padv_builtin_task_RunModelStandards_AHRS_Voter_JUnit.xml
