name: temp

on:
  workflow_dispatch:

jobs:
  job1:
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:  
      - name: Step 1 
        run: ->
         echo "hello"
         echo "hello"
        


