name: Continue on Error Example

on:
  workflow_dispatch:

jobs:
  job1:
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:  
      - name: Step 1 (Failing Step)
        run: exit 1
        

  job2:
    runs-on: ubuntu-latest
    needs: job1
    steps:
      - name: Another Job
        run: echo "This is another job"
