name: Generate and delete Artifact
on:
  workflow_dispatch:

jobs:
  generate-artifact:
    runs-on: ubuntu-latest

    steps:
      - name: Create Artifact
        run: |
          echo "Hello, world!" > hello.txt

      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: my-artifact
          path: hello.txt
          
      - name: Delete artifacts
        uses: geekyeggo/delete-artifact@v2
        with:
          name: my-artifact
          
      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: my-artifact2
          path: hello.txt 
